<?php

/**
 * @file
 * Contains ckeditor_image_velik.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help(). test
 */
function ckeditor_image_velik_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ckeditor_entity_link module.
    case 'help.page.ckeditor_image_velik':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows to insert images in CKEditor.') . '</p>';
      return $output;

    default:
  }
}
